### ISSUE TITLE
[Feature] SportDataAPI service

### ISSUE THREAD

**Issue by jkopyto** [jkopyto/CodersCamp2020.Project.JavaScript.NewsService#18]
### Acceptance criteria
**Functioning service that implements methods from [SportDataAPI](https://app.sportdataapi.com/documentation)**

- [x] Create new service in `service` folder
- [x] Implement proper methods based on proposed functionalities [Wiki](https://github.com/jkopyto/CodersCamp2020.Project.JavaScript.NewsService/wiki/%5BAPI%5D-SportDataApi)
- [x] Test them by console.logging them (see how responses exactly looks like)
- [x] Remove console log and write tests

**Comment by kubaszajna** [comment]
Zrobione
